### PR TITLE
added custom scrollbar

### PR DESCRIPTION
**Pull request by lancerossdev**
I just added custom scrollbar using tailwind-scrollbar. The scrollbar is just a thin scrollbar with the color of zinc-500 on the thumb and zinc-800 on the track. Also, I saw that you don't have package-lock.json on the repo and idk if I should include this in PR. I hope this works 😄.

### CODE REVIEW

**Comment by lancerossdev** [comment]
hey @kevinzunigacuellar, my PR is still not approved and it's behind 3 commits (from my fork) 😭

**Comment by kevinzunigacuellar** [comment]
> hey @kevinzunigacuellar, my PR is still not approved and it's behind 4 commits (from my fork) 😭

I will get to it during the weekend, I haven't forgotten about this 👀

**Comment by kevinzunigacuellar** [comment]
Looks nice! I am not sure why we need a package to add scrollbar functionality, I would like to keep things simple with just plain CSS.

**Comment by lancerossdev** [comment]
> Looks nice! I am not sure why we need a package to add scrollbar functionality, I would like to keep things simple with just plain CSS.

Tailwind does not support webkit custom scrollbar out of the box but then I saw this npm package that does that. I would like to add CSS but since you are using Tailwind on your site, I used the tailwind-scrollbar.

**Pull request merged**
